# Generated by Django 5.1.6 on 2025-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_fullname', models.CharField(max_length=100)),
                ('client_queue_no', models.CharField(max_length=100)),
                ('client_lane_type', models.CharField(max_length=100)),
                ('client_transaction_type', models.CharField(max_length=100)),
                ('client_status', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PacdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
