# Generated by Django 4.2.2 on 2025-07-12 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('divisions', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='For Approval', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_firstname', models.CharField(blank=True, max_length=100)),
                ('client_lastname', models.CharField(blank=True, max_length=100)),
                ('client_org', models.CharField(blank=True, max_length=100)),
                ('client_queue_no', models.PositiveIntegerField(default=1)),
                ('client_lane_type', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=10, null=True)),
                ('client_gender', models.CharField(max_length=10, null=True)),
                ('client_status', models.CharField(default='Pending', max_length=100)),
                ('client_created_date', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(default='System', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_code', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('type_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('timeFrame', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='app.clientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('transaction_details', models.TextField(null=True)),
                ('unit', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('unit_user', models.CharField(max_length=100, null=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(max_length=100, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacd_actions', to='app.clientdetails')),
            ],
        ),
    ]
