# Generated by Django 5.1.6 on 2025-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='unit_person',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
