# Generated by Django 4.2.2 on 2025-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_queue_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
