# Generated by Django 5.2.6 on 2026-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='client_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
