# Generated by Django 5.2.6 on 2026-08-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientdetails_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='public_id',
            new_name='uid',
        ),
    ]
