# Generated by Django 4.2.2 on 2025-03-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_book_alter_clientdetails_client_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='created_date',
            new_name='client_created_date',
        ),
    ]
