# Generated by Django 4.2.2 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_public_id_clientdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
