# Generated by Django 5.1.6 on 2025-07-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servicesdetails_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='service_avail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesdetails',
            name='service_name',
            field=models.TextField(),
        ),
    ]
