# Generated by Django 4.2.2 on 2025-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_created_date_clientdetails_client_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
