# Generated by Django 5.2.6 on 2026-08-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clientdetails_client_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisionLog',
            new_name='TransactionsLog',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
