# Generated by Django 5.1.6 on 2025-03-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_clientdetails_client_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HislotyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ClientDetails', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='app.clientdetails')),
            ],
        ),
    ]
