# Generated by Django 5.1.6 on 2025-08-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_divisionlog_service_avail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='deficiencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='q_deficiencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='service_cc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
