# Generated by Django 5.2.6 on 2026-08-10 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_divisionlog_transactionslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Served', 'Served'), ('Forwarded', 'Forwarded'), ('Skipped', 'Skipped')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('citizen_charter', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('has_deficiency', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('deficiency_details', models.TextField(blank=True, null=True)),
                ('resolved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('csm_rating', models.CharField(blank=True, max_length=30, null=True)),
                ('deficiency_status', models.CharField(blank=True, max_length=50, null=True)),
                ('css_rating', models.CharField(blank=True, max_length=30, null=True)),
                ('forwarded_to_office', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.clientdetails')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TransactionsLog',
        ),
    ]
