# Generated by Django 5.2.6 on 2026-08-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transactionlog_delete_transactionslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='forwarded_to_office',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='forwarded_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.division'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='forwarded_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.unit'),
        ),
    ]
