# Generated by Django 5.1.6 on 2025-08-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_divisionlog_deficiencies_divisionlog_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='process',
        ),
        migrations.RemoveField(
            model_name='divisionlog',
            name='q_deficiencies',
        ),
    ]
