# Generated by Django 4.2.2 on 2025-03-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hislotylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacdUser',
        ),
    ]
