# Generated by Django 4.2.2 on 2025-03-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_pacduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HislotyLog',
            new_name='HisloryLog',
        ),
    ]
