# Generated by Django 5.1.6 on 2025-08-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_divisionlog_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='service_cc',
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='requirements_met',
            field=models.BooleanField(default=False),
        ),
    ]
