# Generated by Django 5.2.6 on 2026-08-11 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_transactionlog_forwarded_to_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
