# Generated by Django 5.1.6 on 2025-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_divisionlog_service_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='cc_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='request_catered',
            field=models.BooleanField(default=False),
        ),
    ]
