# Generated by Django 5.2.6 on 2026-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transactionlog_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUB_ADMIN', 'Sub-Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
