# Generated by Django 5.1.6 on 2025-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_divisionlog_cc_cover_divisionlog_request_catered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='cc_cover',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='request_catered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='requirements_met',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
