# Generated by Django 4.2.2 on 2025-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_accountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
