# Generated by Django 5.2.6 on 2026-08-12 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_accountdetails_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
