# Generated by Django 5.2.6 on 2026-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_transactionlog_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
