# Generated by Django 5.1.6 on 2025-08-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_divisionlog_cc_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetails',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesdetails',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
