# Generated by Django 4.2.2 on 2025-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_accountdetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
