# Generated by Django 5.1.6 on 2025-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_servicesdetails_edition_servicesdetails_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetails',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
