# Generated by Django 4.2.2 on 2025-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_accountdetails_username_accountdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='user',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
