# Generated by Django 5.2.6 on 2026-08-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_transactionlog_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='description',
            new_name='details',
        ),
    ]
