# Generated by Django 5.1.6 on 2025-04-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_accountdetails_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HisloryLog',
            new_name='HistoryLog',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='client_gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
