# Generated by Django 5.1.6 on 2026-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_description_transactionlog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='csm_rating',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='css_rating',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='survey_form',
            field=models.CharField(blank=True, choices=[('CSM', 'CSM'), ('CSS', 'CSS')], max_length=3, null=True),
        ),
    ]
