# Generated by Django 5.1.6 on 2025-08-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_servicesdetails_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesdetails',
            old_name='timeFrame',
            new_name='processing_time',
        ),
    ]
