# Generated by Django 4.2.2 on 2025-08-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_timeframe_servicesdetails_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='unit_person',
        ),
        migrations.RemoveField(
            model_name='divisionlog',
            name='unit_user',
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='pacd_officer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacd_officer', to='app.accountdetails'),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='process_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_owner', to='app.accountdetails'),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_logs', to='app.clientdetails'),
        ),
    ]
