# Generated by Django 5.1.6 on 2026-08-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_transactionlog_csm_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='handled_by',
            new_name='process_owner',
        ),
    ]
