# Generated by Django 5.1.6 on 2025-04-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_divisionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historylog',
            name='ClientDetails',
        ),
    ]
