# Generated by Django 4.2.2 on 2025-08-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_divisionlog_unit_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='user',
        ),
    ]
