# Generated by Django 5.1.6 on 2026-08-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_handled_by_transactionlog_process_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='app.servicesdetails'),
        ),
    ]
