# Generated by Django 5.1.6 on 2025-04-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_historylog_clientdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='action',
        ),
    ]
