# Generated by Django 5.1.6 on 2025-09-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_divisionlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='service_avail',
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicesdetails'),
        ),
    ]
