# Generated by Django 5.1.6 on 2025-04-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_divisionlog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisionlog',
            old_name='remarks',
            new_name='transaction_details',
        ),
    ]
