# Generated by Django 5.1.6 on 2026-08-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_transactionlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='status',
        ),
    ]
