# Generated by Django 5.1.6 on 2025-10-02 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_divisionlog_service_avail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
