# Generated by Django 5.1.6 on 2026-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_transactionlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(blank=True, choices=[('Serving', 'Serving'), ('Served', 'Served')], max_length=20, null=True),
        ),
    ]
