# Generated by Django 4.2.2 on 2025-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_remarks_divisionlog_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='division',
            field=models.CharField(default='PACD', max_length=100),
        ),
    ]
