# Generated by Django 5.1.6 on 2026-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_clientdetails_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='date_forwarded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
