# Generated by Django 5.1.6 on 2026-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_transactionlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_status',
            field=models.CharField(choices=[('Served', 'Served'), ('Serving', 'Serving'), ('Forwarded', 'Forwarded'), ('Skipped', 'Skipped'), ('Waiting', 'Waiting')], default='Waiting', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('Served', 'Served'), ('Serving', 'Serving'), ('Forwarded', 'Forwarded'), ('Skipped', 'Skipped')], max_length=20),
        ),
    ]
