# Generated by Django 5.1.6 on 2026-03-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_divisionlog_date_forwarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisionlog',
            old_name='date_forwarded',
            new_name='dateFrwrd',
        ),
    ]
