# Generated by Django 5.2.6 on 2026-08-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_transactionlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_status',
            field=models.CharField(choices=[('Served', 'Served'), ('Serving', 'Serving'), ('Forwarded', 'Forwarded'), ('Skipped', 'Skipped'), ('Waiting', 'Waiting')], default='Waiting', max_length=100),
        ),
    ]
