# Generated by Django 5.1.6 on 2026-03-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_date_forwarded_divisionlog_datefrwrd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionlog',
            name='dateFrwrd',
        ),
    ]
