# Generated by Django 5.1.6 on 2026-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_transactionlog_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetails',
            name='category',
            field=models.CharField(blank=True, choices=[('External', 'External'), ('Internal', 'Internal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicesdetails',
            name='classification',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Complex', 'Complex'), ('Highly Technical', 'Highly Technical')], max_length=100, null=True),
        ),
    ]
