# Generated by Django 5.1.6 on 2026-04-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_divisionlog_datefrwrd'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='divisionlog',
            table='division_log',
        ),
    ]
