# Generated by Django 4.2.2 on 2025-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_clientdetails_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='division',
        ),
    ]
