# Generated by Django 5.1.6 on 2026-04-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_divisionlog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='divisionlog',
            table='transactions_log',
        ),
    ]
