# Generated by Django 4.2.2 on 2025-04-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_clientdetails_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='client_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='unit_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
