# Generated by Django 5.1.6 on 2026-09-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_transactionlog_pacd_officer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historylog',
            name='client',
        ),
        migrations.DeleteModel(
            name='SessionHistory',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_status',
            field=models.CharField(choices=[('Served', 'Served'), ('Serving', 'Serving'), ('Forwarded', 'Forwarded'), ('Skipped', 'Skipped'), ('Catered', 'Catered'), ('Waiting', 'Waiting')], default='Waiting', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='app.organization'),
        ),
        migrations.DeleteModel(
            name='HistoryLog',
        ),
    ]
