# Generated by Django 4.2.2 on 2026-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_divisionlog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
