# Generated by Django 4.2.2 on 2025-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_clientdetails_client_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionlog',
            name='form',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
