# Generated by Django 4.2.2 on 2026-04-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_divisionlog_transaction_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesdetails',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='servicesdetails',
            name='service_code',
        ),
    ]
