# Generated by Django 4.2.2 on 2025-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_divisionlog_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='transaction_details',
            field=models.TextField(null=True),
        ),
    ]
