# Generated by Django 5.1.6 on 2026-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_organization_remove_historylog_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
