# Generated by Django 4.2.2 on 2026-04-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_servicesdetails_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesdetails',
            name='function',
        ),
    ]
