# Generated by Django 5.1.6 on 2026-09-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_clientdetails_client_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
