# Generated by Django 6.1.1 on 2026-09-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETED', 'Deleted'), ('VIEW', 'View'), ('FORWARDED', 'Forwarded'), ('SERVING', 'Serving'), ('SERVE', 'Serve'), ('SKIP', 'Skip'), ('CATERED', 'Catered'), ('PRINT', 'Print'), ('STATUS_CHANGE', 'Status Change')], max_length=30),
        ),
    ]
