# Generated by Django 4.2.2 on 2025-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_divisionlog_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
