# Generated by Django 4.2.2 on 2025-05-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_clientdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
