# Generated by Django 4.2.2 on 2026-04-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_servicesdetails_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetails',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
