# Generated by Django 5.1.6 on 2026-04-21 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_servicesdetails_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetails',
            name='processing_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True),
        ),
    ]
