# Generated by Django 4.2.2 on 2025-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_divisionlog_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='transaction_details',
            field=models.TextField(null=True),
        ),
    ]
