# Generated by Django 4.2.2 on 2026-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_servicesdetails_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='unit',
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divisionlog',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
