# Generated by Django 4.2.2 on 2025-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_divisionlog_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='auth_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='status',
            field=models.CharField(default='Active', max_length=100, null=True),
        ),
    ]
