# Generated by Django 4.2.2 on 2026-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_clientdetails_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_lane_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
