# Generated by Django 5.1.6 on 2026-04-28 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_clientdetails_client_lane_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.accountdetails')),
                ('division_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='app.divisionlog')),
            ],
            options={
                'db_table': 'transaction_history',
                'ordering': ['-date'],
            },
        ),
    ]
