# Generated by Django 4.2.2 on 2025-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_accountdetails_auth_person_accountdetails_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='auth_person',
            new_name='created_by',
        ),
    ]
