# Generated by Django 5.1.6 on 2026-04-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='division_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.divisionlog'),
        ),
    ]
