# Generated by Django 4.2.2 on 2025-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_auth_person_accountdetails_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='divisions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
