# Generated by Django 4.2.2 on 2025-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_accountdetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
