# Generated by Django 5.1.6 on 2026-04-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_transactionhistory_transaction_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='division_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_log', to='app.divisionlog'),
        ),
    ]
