# Generated by Django 4.2.2 on 2025-06-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_divisionlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
