# Generated by Django 5.1.6 on 2026-04-28 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_transactionhistory_division_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.accountdetails'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='division_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_log', to='app.divisionlog'),
        ),
    ]
