# Generated by Django 5.1.6 on 2026-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_transactionhistory_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
