# Generated by Django 4.2.2 on 2026-04-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_transactionhistory_transaction_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transaction_no',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='app.accountdetails'),
        ),
    ]
