# Generated by Django 4.2.2 on 2025-06-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_sessionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
