# Generated by Django 4.2.2 on 2025-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_sessionhistory_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='client_fullname',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='client_firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='client_lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='client_org',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
