# Generated by Django 5.1.6 on 2026-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_transactionhistory_transaction_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='client_created_date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_status',
            field=models.CharField(default='Waiting', max_length=100),
        ),
    ]
