# Generated by Django 4.2.2 on 2025-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_clientdetails_client_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='client_transaction_type',
        ),
        migrations.AddField(
            model_name='divisionlog',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
