# Generated by Django 5.1.6 on 2026-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_client_created_date_clientdetails_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='deficiencies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='form',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
