# Generated by Django 4.2.2 on 2025-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_clientdetails_client_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='unit',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
