# Generated by Django 4.2.2 on 2026-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_transactionhistory_deficiencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
