# Generated by Django 4.2.2 on 2026-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_transactionhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
