# Generated by Django 5.1.6 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_accountdetails_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcitivtyLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
