# Generated by Django 5.1.6 on 2026-05-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_acitivtylogs'),
        ('app', '0040_useractivitylog'),
    ]

    operations = [
    ]
