# Generated by Django 5.1.6 on 2026-05-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_merge_0040_acitivtylogs_0040_useractivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcitivtyLogs',
        ),
    ]
