# Generated by Django 5.1.6 on 2026-05-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_delete_acitivtylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetails',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
